baseURL = 'https://haito4.github.io'
languageCode = 'en-au'
title = 'Artisian DSP Documentation'

[module]
    [[module.imports]]
        path = 'github.com/hugomods/images'
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[params.social]
    github = "Haito4/ArtisianDSP"

[params.docs]
    intLinkToolTip = true
    darkMode = true
    breadcrumbs = true
    scrollSpy = true
    lastMod = true
    extLinkNewTab = true
    
    backToTop = true
    navDesc = true
    
    sidebarIcons = true
    titleIcon = true
    
    
[params.flexsearch]
  enabled = false

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10


    
